In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi','children', 'sex_male', 'smoker_yes']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent=dataset[['charges']]

In [10]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.20,random_state=0)

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],
'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}

# fitting the model for grid search
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(x_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [17]:
re=grid.cv_results_
print("TheR_score valueforbestparameter{}:".format(grid.best_params_))

TheR_score valueforbestparameter{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:

In [18]:
 table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.264074,0.011577,0.050109,0.003697,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.037325,0.021048,-0.036168,-0.084435,-0.117458,-0.050867,0.047186,36
1,0.178116,0.083746,0.015682,0.001884,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.018511,0.085272,0.033035,-0.010290,-0.053604,0.014585,0.046089,31
2,0.107516,0.002870,0.022602,0.002184,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.015530,0.084609,0.027106,-0.021105,-0.053763,0.010475,0.046737,34
3,0.076192,0.004815,0.013149,0.000838,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.390629,0.478401,0.431247,0.387305,0.354880,0.408492,0.042537,25
4,0.095895,0.002447,0.041401,0.002046,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.037397,0.021106,-0.036096,-0.084348,-0.117601,-0.050867,0.047232,35
5,0.065299,0.000968,0.014041,0.000608,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.019948,0.084177,0.031529,-0.011743,-0.051330,0.014516,0.045159,32
6,0.099788,0.001373,0.020930,0.000966,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.015867,0.084351,0.026787,-0.021351,-0.053233,0.010484,0.046528,33
7,0.067109,0.006912,0.010722,0.002533,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.390629,0.478401,0.431247,0.387305,0.354880,0.408492,0.042537,25
8,0.094094,0.007628,0.045091,0.002781,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.282882,0.365482,0.289946,0.246873,0.215599,0.280156,0.050317,27
9,0.080461,0.004112,0.014874,0.003128,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.540280,0.610001,0.573841,0.556588,0.459042,0.547950,0.050117,22
10,0.108467,0.003111,0.020316,0.001316,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.479965,0.536934,0.507258,0.461129,0.440349,0.485127,0.034004,24
11,0.081306,0.004383,0.012267,0.000734,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.585412,0.629734,0.617429,0.584651,0.552153,0.593876,0.027343,19
12,0.100865,0.001466,0.042309,0.004130,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.282276,0.365919,0.290460,0.247487,0.214634,0.280155,0.050649,28
13,0.074030,0.005269,0.014939,0.001692,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.544403,0.607290,0.570094,0.553578,0.465910,0.548255,0.046445,21
14,0.104571,0.002646,0.021114,0.000880,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.481860,0.537004,0.507621,0.460342,0.440683,0.485502,0.034049,23
15,0.081270,0.005522,0.015318,0.002343,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.585412,0.629734,0.617429,0.584651,0.552153,0.593876,0.027343,19
16,0.115787,0.003131,0.041779,0.002668,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.769052,0.780447,0.762308,0.767010,0.691774,0.754118,0.031737,12
17,0.101401,0.008714,0.013494,0.001231,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.825149,0.819834,0.811681,0.836272,0.740817,0.806751,0.033920,8
18,0.116083,0.002925,0.020662,0.001683,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.306842,0.216677,0.325978,0.160679,0.309872,0.264010,0.064336,30
19,0.096977,0.004278,0.013811,0.000718,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.651795,0.629307,0.637008,0.650704,0.601740,0.634111,0.018262,13
20,0.114494,0.003949,0.036724,0.005134,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.768851,0.780630,0.762558,0.767361,0.691206,0.754121,0.032014,11
21,0.103446,0.014863,0.012880,0.001481,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.826301,0.819682,0.811392,0.836006,0.742592,0.807195,0.033293,7
22,0.112861,0.004540,0.021777,0.000837,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.310695,0.222521,0.334635,0.173480,0.301074,0.268481,0.060594,29
23,0.102215,0.005786,0.012899,0.002743,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.651795,0.629307,0.637008,0.650704,0.601740,0.634111,0.018262,13
24,0.115812,0.002151,0.039432,0.001951,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.828351,0.814160,0.797293,0.823797,0.735907,0.799902,0.033722,9
25,0.180498,0.046180,0.013862,0.001395,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.839418,0.822365,0.815980,0.839691,0.750080,0.813507,0.033059,4
26,0.116029,0.006317,0.021445,0.000552,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.451430,-0.745829,-0.639843,-0.989296,-0.468395,-0.658958,0.198200,37
27,0.150605,0.041176,0.013264,0.001689,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.657836,0.624504,0.632004,0.649113,0.597156,0.632123,0.021121,15
28,0.115074,0.005210,0.041897,0.003219,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.828193,0.814198,0.797419,0.823872,0.735771,0.799891,0.033759,10
29,0.185801,0.038140,0.013856,0.000787,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.839371,0.822322,0.815970,0.839763,0.750572,0.813600,0.032872,3
30,0.117622,0.006924,0.020692,0.000915,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.472104,-1.109682,-0.615668,-0.962824,-0.525840,-0.737223,0.252732,38
31,0.155191,0.046098,0.013637,0.001566,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.657836,0.624504,0.632004,0.649113,0.597156,0.632123,0.021121,15
32,0.131306,0.007782,0.040461,0.000935,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.838764,0.823122,0.805058,0.836063,0.741767,0.808955,0.035647,6
33,0.329179,0.124747,0.014819,0.001224,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.840456,0.821812,0.813557,0.838468,0.754565,0.813771,0.031280,2
34,0.116825,0.003341,0.021386,0.000827,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.789185,-3.304977,-2.288641,-1.806489,-1.794049,-2.196668,0.586036,39
35,0.157122,0.044742,0.013680,0.001822,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.658338,0.624508,0.631999,0.646221,0.597151,0.631644,0.020813,17
36,0.130173,0.008791,0.039592,0.002433,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.838645,0.823178,0.805177,0.836119,0.741674,0.808959,0.035673,5
37,0.240929,0.034241,0.012543,0.002004,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.840472,0.821813,0.813520,0.838583,0.754680,0.813814,0.031257,1
38,0.108162,0.004636,0.022594,0.002565,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.843270,-2.497666,-2.236821,-2.604137,-1.865146,-2.209408,0.313761,40
39,0.149538,0.040413,0.012794,0.000430,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.658338,0.624508,0.631999,0.646221,0.597151,0.631644,0.020813,17

In [21]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 43
BMI: 12
Children: 3
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1